spring:
  application:
    name: credit-management-system
  datasource:
    url: jdbc:postgresql://localhost:5432/credit-ms
    username: root
    password: 12345
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: create
    database: postgresql
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    properties:
      hibernate:
        format_sql: true
  jackson:
    date-format: dd-MM-yyyy
  thymeleaf:
    date-format: dd-MM-yyyy
    datetime-format: dd-MM-yyyy HH:mm:ss